// Code generated by mockery v2.20.0. DO NOT EDIT.

package rollup

import (
	context "context"
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// MockRollup is an autogenerated mock type for the Rollup type
type MockRollup struct {
	mock.Mock
}

type MockRollup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRollup) EXPECT() *MockRollup_Expecter {
	return &MockRollup_Expecter{mock: &_m.Mock}
}

// CheckBalance provides a mock function with given fields: searcher
func (_m *MockRollup) CheckBalance(searcher common.Address) *big.Int {
	ret := _m.Called(searcher)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(common.Address) *big.Int); ok {
		r0 = rf(searcher)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// MockRollup_CheckBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckBalance'
type MockRollup_CheckBalance_Call struct {
	*mock.Call
}

// CheckBalance is a helper method to define mock.On call
//   - searcher common.Address
func (_e *MockRollup_Expecter) CheckBalance(searcher interface{}) *MockRollup_CheckBalance_Call {
	return &MockRollup_CheckBalance_Call{Call: _e.mock.On("CheckBalance", searcher)}
}

func (_c *MockRollup_CheckBalance_Call) Run(run func(searcher common.Address)) *MockRollup_CheckBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Address))
	})
	return _c
}

func (_c *MockRollup_CheckBalance_Call) Return(_a0 *big.Int) *MockRollup_CheckBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRollup_CheckBalance_Call) RunAndReturn(run func(common.Address) *big.Int) *MockRollup_CheckBalance_Call {
	_c.Call.Return(run)
	return _c
}

// CheckBalanceRemote provides a mock function with given fields: searcher
func (_m *MockRollup) CheckBalanceRemote(searcher common.Address) (*big.Int, error) {
	ret := _m.Called(searcher)

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Address) (*big.Int, error)); ok {
		return rf(searcher)
	}
	if rf, ok := ret.Get(0).(func(common.Address) *big.Int); ok {
		r0 = rf(searcher)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Address) error); ok {
		r1 = rf(searcher)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRollup_CheckBalanceRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckBalanceRemote'
type MockRollup_CheckBalanceRemote_Call struct {
	*mock.Call
}

// CheckBalanceRemote is a helper method to define mock.On call
//   - searcher common.Address
func (_e *MockRollup_Expecter) CheckBalanceRemote(searcher interface{}) *MockRollup_CheckBalanceRemote_Call {
	return &MockRollup_CheckBalanceRemote_Call{Call: _e.mock.On("CheckBalanceRemote", searcher)}
}

func (_c *MockRollup_CheckBalanceRemote_Call) Run(run func(searcher common.Address)) *MockRollup_CheckBalanceRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Address))
	})
	return _c
}

func (_c *MockRollup_CheckBalanceRemote_Call) Return(_a0 *big.Int, _a1 error) *MockRollup_CheckBalanceRemote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRollup_CheckBalanceRemote_Call) RunAndReturn(run func(common.Address) (*big.Int, error)) *MockRollup_CheckBalanceRemote_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuilderID provides a mock function with given fields:
func (_m *MockRollup) GetBuilderID() common.Address {
	ret := _m.Called()

	var r0 common.Address
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	return r0
}

// MockRollup_GetBuilderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuilderID'
type MockRollup_GetBuilderID_Call struct {
	*mock.Call
}

// GetBuilderID is a helper method to define mock.On call
func (_e *MockRollup_Expecter) GetBuilderID() *MockRollup_GetBuilderID_Call {
	return &MockRollup_GetBuilderID_Call{Call: _e.mock.On("GetBuilderID")}
}

func (_c *MockRollup_GetBuilderID_Call) Run(run func()) *MockRollup_GetBuilderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRollup_GetBuilderID_Call) Return(_a0 common.Address) *MockRollup_GetBuilderID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRollup_GetBuilderID_Call) RunAndReturn(run func() common.Address) *MockRollup_GetBuilderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMinimalStake provides a mock function with given fields: builder
func (_m *MockRollup) GetMinimalStake(builder common.Address) *big.Int {
	ret := _m.Called(builder)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(common.Address) *big.Int); ok {
		r0 = rf(builder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// MockRollup_GetMinimalStake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMinimalStake'
type MockRollup_GetMinimalStake_Call struct {
	*mock.Call
}

// GetMinimalStake is a helper method to define mock.On call
//   - builder common.Address
func (_e *MockRollup_Expecter) GetMinimalStake(builder interface{}) *MockRollup_GetMinimalStake_Call {
	return &MockRollup_GetMinimalStake_Call{Call: _e.mock.On("GetMinimalStake", builder)}
}

func (_c *MockRollup_GetMinimalStake_Call) Run(run func(builder common.Address)) *MockRollup_GetMinimalStake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Address))
	})
	return _c
}

func (_c *MockRollup_GetMinimalStake_Call) Return(_a0 *big.Int) *MockRollup_GetMinimalStake_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRollup_GetMinimalStake_Call) RunAndReturn(run func(common.Address) *big.Int) *MockRollup_GetMinimalStake_Call {
	_c.Call.Return(run)
	return _c
}

// GetStake provides a mock function with given fields: builder, searcher
func (_m *MockRollup) GetStake(builder common.Address, searcher common.Address) *big.Int {
	ret := _m.Called(builder, searcher)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(common.Address, common.Address) *big.Int); ok {
		r0 = rf(builder, searcher)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// MockRollup_GetStake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStake'
type MockRollup_GetStake_Call struct {
	*mock.Call
}

// GetStake is a helper method to define mock.On call
//   - builder common.Address
//   - searcher common.Address
func (_e *MockRollup_Expecter) GetStake(builder interface{}, searcher interface{}) *MockRollup_GetStake_Call {
	return &MockRollup_GetStake_Call{Call: _e.mock.On("GetStake", builder, searcher)}
}

func (_c *MockRollup_GetStake_Call) Run(run func(builder common.Address, searcher common.Address)) *MockRollup_GetStake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Address), args[1].(common.Address))
	})
	return _c
}

func (_c *MockRollup_GetStake_Call) Return(_a0 *big.Int) *MockRollup_GetStake_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRollup_GetStake_Call) RunAndReturn(run func(common.Address, common.Address) *big.Int) *MockRollup_GetStake_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx
func (_m *MockRollup) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRollup_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRollup_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRollup_Expecter) Run(ctx interface{}) *MockRollup_Run_Call {
	return &MockRollup_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockRollup_Run_Call) Run(run func(ctx context.Context)) *MockRollup_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRollup_Run_Call) Return(_a0 error) *MockRollup_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRollup_Run_Call) RunAndReturn(run func(context.Context) error) *MockRollup_Run_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRollup interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRollup creates a new instance of MockRollup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRollup(t mockConstructorTestingTNewMockRollup) *MockRollup {
	mock := &MockRollup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
