name: Go Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Download Go modules
      run: go mod download

    - name: Test
      run: |
        cd pkg/
        go test -v ./...
